FROM {{ namespace }}/{{ infra_image_prefix }}prometheus-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% import "macros.j2" as macros with context %}

{% block prometheus_libvirt_exporter_header %}{% endblock %}

{% if base_distro in ['centos'] %}
    {% set prometheus_libvirt_exporter_packages = [
        'go',
        'libvirt-devel',
        'git',
    ] %}
{% elif base_distro in ['debian', 'ubuntu'] %}
    {% set prometheus_libvirt_exporter_packages = [
        'golang-go',
        'libvirt-dev',
        'git',
    ] %}
{% endif %}

{{ macros.install_packages(prometheus_libvirt_exporter_packages | customizable("packages")) }}

{% block prometheus_libvirt_exporter_version %}
ARG prometheus_libvirt_exporter_version=2.1.1
ARG prometheus_libvirt_exporter_url=https://github.com/AlexZzz/libvirt-exporter/archive/refs/tags
{% endblock %}

{% block prometheus_libvirt_exporter_install %}
ENV GOPATH=/build
RUN mkdir /build \
    && cd /build \
    && curl -sSL -o libvirt-exporter.tar.gz ${prometheus_libvirt_exporter_url}/${prometheus_libvirt_exporter_version}.tar.gz  \
    && tar xvf libvirt-exporter.tar.gz \
    && cd libvirt-exporter-${prometheus_libvirt_exporter_version} \
    && go build -mod vendor \
    && install -m 0755 libvirt-exporter /opt/ \
    && rm -rf /build

{% endblock %}

{% block prometheus_libvirt_exporter_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER prometheus
