FROM {{ namespace }}/{{ image_prefix }}monasca-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block monasca_thresh_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% elif install_type == 'source' %}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
    {% set monasca_thresh_packages = [
        'java-1.8.0-openjdk',
        'maven',
        'git'
    ] %}
{% elif base_distro in ['debian', 'ubuntu'] %}
    {% set monasca_thresh_packages = [
        'default-jre',
        'maven',
        'git'
    ] %}
{% endif %}

{{ macros.install_packages(monasca_thresh_packages | customizable("packages")) }}

# TODO: All we want is the client here..
{% block storm_version %}
ENV storm_version=1.1.2
ENV storm_url=http://www.mirrorservice.org/sites/ftp.apache.org/storm/apache-storm-${storm_version}/apache-storm-${storm_version}.tar.gz
ENV storm_pkg_sha512sum=4ec7554d4e242c5cfa3b010f63b2ed65866d0768bfa04c7ae87004d21994041ef25b198a236a87f14ac3b36b698f117338080d9b7d9c0f561b7de256bf2e10d2
{% endblock %}

RUN curl -sSL -o /tmp/storm.tgz ${storm_url} \
    && echo "${storm_pkg_sha512sum} /tmp/storm.tgz" | sha512sum -c \
    && mkdir /opt/storm \
    && tar --strip 1 -xvf /tmp/storm.tgz -C /opt/storm \
    && rm -f /tmp/storm.tgz

#ADD monasca-common-archive /monasca-common-source
ENV monasca_common_url=https://github.com/openstack/monasca-common/archive/master.tar.gz
RUN curl -sSL -o /tmp/monasca-common.tgz ${monasca_common_url} \
    && mkdir /monasca-common-source \
    && tar --strip 1 -xvf /tmp/monasca-common.tgz -C /monasca-common-source \
    && rm -f /tmp/monasca-common.tgz

# Zuul tarball job is borked so use github for now
ENV monasca_thresh_url=https://github.com/openstack/monasca-thresh/archive/master.tar.gz
RUN curl -sSL -o /tmp/monasca-thresh.tgz ${monasca_thresh_url} \
    && mkdir /monasca-thresh-source \
    && tar --strip 1 -xvf /tmp/monasca-thresh.tgz -C /monasca-thresh-source \
    && rm -f /tmp/monasca-thresh.tgz


{% block monasca_thresh_source_install %}
# Use this? WORKDIR /usr/local/src/
RUN cd /monasca-common-source/java \
    && mvn clean install -DskipTests \
    && cd /monasca-thresh-source/thresh \
    && mvn clean package -DskipTests
{% endblock %}

{% endif %}

{% block monasca_thresh_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER monasca
