FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block caso_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if distro_python_version.startswith('3') %}
{% set caso_python_packages = [
        'python3',
        'python3-pip'
] %}
{% else %}
{% set caso_python_packages = [
        'python',
        'python-pip'
] %}
{% endif %}

{{ macros.install_packages(caso_python_packages) }}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
    {% set caso_packages = [
        'cronie',
        'wget',
    ] %}
{% elif base_distro in ['debian', 'ubuntu'] %}
    {% set caso_packages = [
        'cron',
    ] %}
{% endif %}

{{ macros.install_packages(caso_packages | customizable("packages")) }}

{{ macros.configure_user(name='caso') }}

{% if distro_python_version.startswith('3') %}
{% set caso_pip_packages = [
    'caso'
] %}
{% else %}
{% set caso_pip_packages = [
    'caso==1.4.0'
] %}

RUN wget https://bootstrap.pypa.io/pip/2.7/get-pip.py
RUN python get-pip.py
RUN pip -V
RUN pip install --upgrade setuptools

{% endif%}

RUN {{ macros.install_pip(["pip"], constraints = false) }}

RUN {{ macros.install_pip(caso_pip_packages | customizable("pip_packages"),  constraints = false) }} \
    && mkdir -p /etc/caso \
    && chown -R caso: /etc/caso

COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN touch /usr/local/bin/kolla_caso_extend_start \
    && chmod 755 /usr/local/bin/kolla_extend_start /usr/local/bin/kolla_caso_extend_start

{% block caso_base_footer %}{% endblock %}
