FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block mariadb_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='mysql') }}

{# NOTE(mnasiadka): Using AppStream packages on CS10 for now #}
{% if base_package_type == 'rpm' %}
    {% set mariadb_base_packages = [
        'mariadb',
    ] %}

{% elif base_package_type == 'deb' %}
{{ macros.enable_extra_repos(['mariadb']) }}
    {% set mariadb_base_packages = [
        'mariadb-client',
    ] %}
{% endif %}

{{ macros.install_packages(mariadb_base_packages | customizable("packages")) }}

{% block mariadb_healthcheck_version %}
ARG mariadb_healthcheck_version=11.4
ARG mariadb_healthcheck_url=https://raw.githubusercontent.com/MariaDB/mariadb-docker/refs/heads/master/${mariadb_healthcheck_version}/healthcheck.sh
{% endblock %}

RUN curl -o /usr/bin/healthcheck.sh ${mariadb_healthcheck_url} \
    && chmod 755 /usr/bin/healthcheck.sh

{{ macros.kolla_patch_sources() }}

{% block mariadb_base_footer %}{% endblock %}
