FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block logstash_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='logstash', shell='/bin/bash', homedir='/usr/share/logstash') }}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
        {% set logstash_packages = [
            'logstash',
            'java-1.8.0-openjdk'
        ] %}
        ENV JAVA_HOME /usr/lib/jvm/jre-1.8.0-openjdk/
    {% elif base_distro in ['debian', 'ubuntu'] %}

        RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
            && /bin/false
    {% endif %}

{% elif install_type == 'source' %}
    RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

{% endif %}

{{ macros.install_packages(logstash_packages | customizable("packages")) }}
COPY extend_start.sh /usr/local/bin/kolla_extend_start

RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block logstash_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER logstash
