FROM {{ namespace }}/{{ image_prefix }}prometheus-base:{{ tag }}
{% block labels %}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"
{% endblock %}

{% block prometheus_cadvisor_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% block prometheus_cadvisor_repository_version %}
ARG prometheus_cadvisor_version=0.49.1
{% if debian_arch == 'arm64' %}
ARG prometheus_cadvisor_sha256sum=c535f46d789599f25c7c680af193d4402da27a98d9828eb2ec916af6256e0c0c
{% else %}
ARG prometheus_cadvisor_sha256sum=1d5cc701a3fcdf1e8ed1c86da5304b896a6997d9e6673139e78a6f87812495b0
{% endif %}
ARG prometheus_cadvisor_url=https://github.com/google/cadvisor/releases/download/v${prometheus_cadvisor_version}/cadvisor-v${prometheus_cadvisor_version}-linux-{{debian_arch}}
{% endblock %}


{% block prometheus_cadvisor_install %}
RUN curl -o /tmp/cadvisor ${prometheus_cadvisor_url} \
    && echo "${prometheus_cadvisor_sha256sum} /tmp/cadvisor" | sha256sum -c \
    && mv /tmp/cadvisor /opt \
    && chmod 0755 /opt/cadvisor
{% endblock %}


{% block prometheus_cadvisor_footer %}{% endblock %}
{% block footer %}{% endblock %}
