---
- project:
    templates:
      - openstack-python3-zed-jobs
      - openstack-python3-zed-jobs-arm64
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - periodic-stable-jobs
