---
name: Upstream Sync
'on':
  schedule:
    - cron: "15 8 * * 1"
  workflow_dispatch:
jobs:
  upstream-sync:
    runs-on: ubuntu-20.04
    env:
      downstream-prefix: stackhpc
      upstream-prefix: openstack:stable
    strategy:
      fail-fast: false
      matrix:
        branch: [xena, wallaby, victoria]
    steps:
      - name: Create PR ${{ format('{0}/{1}', env.downstream-prefix, matrix.branch) }} with ${{ format('{0}/{1}', env.upstream-prefix, matrix.branch) }}
        uses: actions/github-script@9ac08808f993958e9de277fe43a64532a609130e
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'Synchronise ${{ matrix.branch }} with ${{ format('{0}/{1}', env.upstream-prefix, matrix.branch) }}',
              owner,
              repo,
              head: '${{ format('{0}/{1}', env.upstream-prefix, matrix.branch) }}',
              base: '${{ format('{0}/{1}', env.downstream-prefix, matrix.branch) }}',
              maintainer_can_modify: false,
              body: [
                'This is an automated pull request.'
              ].join('\n')
            });
